(() => {
  'use strict';

  const STORE = 'okello_food_tracker_v3';
  const SAT_STORE = 'okello_satiety_v1';
  const PHOTO_STORE = 'okello_photo_notes_v1';
  const $ = id => document.getElementById(id);
  const qs = (s, r=document) => r.querySelector(s);
  const qsa = (s, r=document) => Array.from(r.querySelectorAll(s));
  const round1 = n => Math.round((Number(n)||0)*10)/10;
  const clamp = (n,a,b) => Math.min(b,Math.max(a,n));
  const todayKey = () => new Date().toISOString().slice(0,10);
  const esc = s => String(s ?? '').replace(/[&<>\"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
  const uid = p => (crypto.randomUUID ? p+'_'+crypto.randomUUID() : p+'_'+Date.now()+'_'+Math.random().toString(36).slice(2));

  const todayPanel = $('tab-today');
  const foodsPanel = $('tab-foods');
  const historyPanel = $('tab-history');
  const settingsPanel = $('tab-settings');
  const catalog = window.OkelloFoodCatalog;
  if (!todayPanel || !foodsPanel || !historyPanel || !settingsPanel || !catalog) return;

  function readState(){ try { return JSON.parse(localStorage.getItem(STORE)||'{}')||{}; } catch(_){ return {}; } }
  function writeState(s){ try { localStorage.setItem(STORE,JSON.stringify(s)); } catch(_){} }
  function toast(msg){ const t=$('toast'); if(!t)return; t.textContent=msg; t.classList.add('show'); clearTimeout(toast.t); toast.t=setTimeout(()=>t.classList.remove('show'),1900); }
  function currentState(){ const s=readState(); s.targets=s.targets||{calories:2300,protein:150}; s.logs=s.logs||{}; s.customFoods=Array.isArray(s.customFoods)?s.customFoods:[]; s.recipes=Array.isArray(s.recipes)?s.recipes:[]; s.weightLogs=Array.isArray(s.weightLogs)?s.weightLogs:[]; s.mealTemplates=Array.isArray(s.mealTemplates)?s.mealTemplates:[]; return s; }
  function todayEntries(){ return currentState().logs[todayKey()]||[]; }
  function totals(entries=todayEntries()){ return entries.reduce((a,x)=>({kcal:a.kcal+(+x.kcal||0),protein:a.protein+(+x.protein||0),fibre:a.fibre+(+x.fibre||0)}),{kcal:0,protein:0,fibre:0}); }
  function remaining(){ const s=currentState(), t=totals(); return {kcal:Math.max(0,(+s.targets.calories||2300)-t.kcal),protein:Math.max(0,(+s.targets.protein||150)-t.protein)}; }
  function clickTab(name){ qs(`.tab[data-tab="${name}"]`)?.click(); }

  // One source of truth: every smart feature reads the catalogue exposed by app.js.
  function getFood(id){ return catalog.getById(id); }
  function customById(id){ return catalog.getById(id); }
  function customByName(term){ return catalog.findByName(term); }
  function calc(food,g){ return catalog.calc(food,g); }
  function normaliseName(v){ return String(v||'').toLowerCase().replace(/\([^)]*\)/g,' ').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim(); }
  function guessCatalogFood(text){
    let q=normaliseName(text)
      .replace(/\b\d+(?:\.\d+)?\b/g,' ')
      .replace(/\b(?:kg|kilo|kilograms?|g|gram|grams|ml|millilitres?|milliliters?|l|litres?|liters?|tbsp|tablespoons?|tsp|teaspoons?|slice|slices|spoon|spoons|one|two|three|four|five|six|i|had|ate|have|some|of|a|an|the|with|and)\b/g,' ')
      .replace(/\s+/g,' ').trim();
    if(!q) return null;
    const direct=catalog.findByName(q); if(direct) return direct;
    let best=null,bestLen=0;
    for(const f of catalog.all()){
      const names=[f.name,String(f.name||'').replace(/\([^)]*\)/g,' '),String(f.name||'').split('/')[0]];
      for(const n0 of names){
        const n=normaliseName(n0); if(n.length<3) continue;
        if((q.includes(n)||n.includes(q)) && Math.min(n.length,q.length)>bestLen){best=f;bestLen=Math.min(n.length,q.length);}
      }
    }
    return best?{...best}:null;
  }
  function logItems(items,meal){ const s=currentState(); const k=todayKey(); s.logs[k]=s.logs[k]||[]; items.forEach(it=>{ const f=getFood(it.id)||it.food; if(!f||!(it.grams>0))return; const c=calc(f,it.grams); s.logs[k].push({id:uid('log'),foodId:f.id||it.id,name:f.name,emoji:f.emoji||'🍽️',grams:round1(it.grams),meal:meal||'Other',kcal:c.kcal,protein:c.protein,fibre:c.fibre,ts:Date.now(),source:it.source||'smart'}); }); writeState(s); location.reload(); }

  const css=document.createElement('style');
  css.textContent=`
    .smart-card{background:var(--white);border:1px solid var(--rule);border-radius:20px;padding:18px;margin:14px 0;box-shadow:var(--shadow)}
    .smart-card h3{margin:0}.smart-card p{margin:6px 0;color:var(--muted)}.smart-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.smart-grid.three{grid-template-columns:repeat(3,1fr)}
    .smart-stat{background:var(--tint);border-radius:14px;padding:12px}.smart-stat span{display:block;color:var(--muted);font-size:.74rem}.smart-stat strong{display:block;color:var(--forest);font-size:1.25rem;margin-top:2px}
    .smart-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.smart-primary,.smart-secondary{min-height:44px;border-radius:12px;font-weight:800;padding:10px 14px}.smart-primary{border:0;background:var(--forest);color:#fff}.smart-secondary{border:1px solid var(--forest);background:#fff;color:var(--forest)}
    .smart-input,.smart-select,.smart-textarea{width:100%;min-height:46px;border:1px solid var(--rule);border-radius:12px;background:#fff;color:var(--ink);padding:10px 12px;font-size:16px}.smart-textarea{min-height:92px;resize:vertical}
    .smart-row{display:grid;grid-template-columns:1fr 1fr;gap:10px}.smart-result{margin-top:12px;padding:12px;background:var(--tint);border-radius:14px;color:var(--ink)}.smart-result strong{color:var(--forest)}
    .meal-suggestion{display:grid;grid-template-columns:1fr auto;gap:12px;padding:12px 0;border-bottom:1px solid var(--rule)}.meal-suggestion:last-child{border-bottom:0}.meal-suggestion small{display:block;color:var(--muted)}
    .parsed-list{display:grid;gap:8px;margin-top:10px}.parsed-row{display:grid;grid-template-columns:1fr 100px auto;gap:8px;align-items:center}.parsed-row small{display:block;color:var(--muted)}
    .plate-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.plate-total{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-top:12px;padding:12px;background:var(--tint);border-radius:14px}.plate-total strong{font-size:1.2rem;color:var(--clay)}
    .sat-buttons{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:10px}.sat-buttons button{min-height:44px;border:1px solid var(--rule);border-radius:12px;background:#fff;color:var(--ink);font-weight:800}.sat-buttons button.active{background:var(--forest);color:#fff;border-color:var(--forest)}
    .week-insights{display:grid;gap:8px}.insight{padding:10px 12px;background:var(--tint);border-radius:12px;color:var(--ink)}
    .label-scan-preview{max-width:100%;max-height:220px;object-fit:contain;border-radius:12px;border:1px solid var(--rule);margin-top:10px}.ocr-progress{font-size:.82rem;color:var(--muted);margin-top:8px}
    .ask-box{display:grid;grid-template-columns:1fr auto;gap:8px}.ask-response{margin-top:10px;padding:12px;border-left:4px solid var(--gold);background:var(--tint);border-radius:10px;color:var(--ink)}
    .photo-box{display:grid;grid-template-columns:120px 1fr;gap:12px;align-items:start}
    @media(max-width:700px){.smart-grid,.smart-grid.three,.smart-row,.plate-grid{grid-template-columns:1fr}.parsed-row{grid-template-columns:1fr 90px}.parsed-row .smart-secondary{grid-column:1/-1}.photo-box{grid-template-columns:1fr}.ask-box{grid-template-columns:1fr}.sat-buttons{grid-template-columns:1fr}}
  `;
  document.head.appendChild(css);

  const composer=document.createElement('section'); composer.className='smart-card'; composer.innerHTML=`
    <p class="eyebrow">SMART MEAL COMPOSER</p><h3>What should I eat now?</h3><p>Build a meal around the calories and protein you still have left.</p>
    <div class="smart-row"><label>Meal<select id="smartMealType" class="smart-select"><option>Lunch</option><option selected>Dinner</option><option>Snack</option></select></label><label>Style<select id="smartMealStyle" class="smart-select"><option value="ghana">Ghanaian</option><option value="world">World mix</option><option value="highprotein">High protein</option><option value="light">Lighter</option></select></label></div>
    <div id="smartMealStats" class="smart-grid" style="margin-top:10px"></div><div id="smartMealList" class="smart-result"></div>`;
  const quickAdd=qs('.quick-add-card',todayPanel); if(quickAdd) quickAdd.insertAdjacentElement('beforebegin',composer); else todayPanel.appendChild(composer);

  const mealSets={
    ghana:[['ghana_waakye','egg','tilapia'],['banku','tilapia','ghana_okro_stew'],['ghana_fufu','goat','light_soup'],['plantain','beans','egg'],['yam','ghana_kontomire_stew','egg']],
    world:[['world_biryani_chicken','world_greek_salad'],['world_chicken_curry','world_couscous','world_greek_salad'],['world_tandoori_chicken','world_bulgur','world_greek_salad'],['world_tofu_firm','world_jasmine_rice','world_kimchi'],['world_sashimi_salmon','world_soba','world_edamame'],['world_pho_beef','world_spring_roll_fresh']],
    highprotein:[['chicken','rice','veg'],['tilapia','potato','veg'],['salmon','potato','veg'],['beef','rice','veg'],['sardines','egg','cottage']],
    light:[['tilapia','veg','potato'],['chicken','veg','plantain'],['lentils','veg','egg'],['salmon','veg','potato']]
  };
  function resolve(id){ return getFood(id) || customById(id) || customByName(String(id||'').replace(/^(?:ghana|world)_/,'').replace(/_/g,' ')); }
  function buildMealSuggestion(ids,budget){
    const fs=ids.map(resolve).filter(Boolean); if(fs.length<2)return null;
    const weights=fs.map(f=> f.cat==='Protein'?.42 : f.cat==='Starch'?.34 : (f.cat==='Soup'||f.cat==='Complete meal'||f.cat==='Recipes')?.50 : f.cat==='Vegetables'?.15 : .2);
    const wsum=weights.reduce((a,b)=>a+b,0); const items=[]; let totalK=0,totalP=0;
    fs.forEach((f,i)=>{ const itemBudget=budget*(weights[i]/wsum); let g=itemBudget/(f.kcal/100); const min=+f.min||(+f.portion||100)*.7,max=+f.max||(+f.portion||100)*1.35; g=clamp(g,min,max); g=Math.max(5,Math.round(g/5)*5); const c=calc(f,g); totalK+=c.kcal;totalP+=c.protein;items.push({id:f.id||ids[i],food:f,grams:g}); });
    if(totalK>budget){ const scale=budget/totalK; totalK=0;totalP=0;items.forEach(it=>{it.grams=Math.max(5,Math.round(it.grams*scale/5)*5);const c=calc(it.food,it.grams);totalK+=c.kcal;totalP+=c.protein;}); }
    return {items,kcal:totalK,protein:totalP};
  }
  function renderComposer(){
    const rem=remaining(); $('smartMealStats').innerHTML=`<div class="smart-stat"><span>Calories left</span><strong>${Math.round(rem.kcal).toLocaleString()}</strong></div><div class="smart-stat"><span>Protein left</span><strong>${Math.round(rem.protein)} g</strong></div>`;
    const style=$('smartMealStyle').value, meal=$('smartMealType').value; const share=meal==='Lunch'?.30:meal==='Dinner'?.45:.15; const target=Math.min(rem.kcal,(currentState().targets.calories||2300)*share); const candidates=(mealSets[style]||mealSets.ghana).map(ids=>buildMealSuggestion(ids,target)).filter(Boolean).sort((a,b)=>b.protein-a.protein).slice(0,3);
    if(!candidates.length){$('smartMealList').innerHTML='Log more foods or add recipes to unlock suggestions.';return;}
    $('smartMealList').innerHTML=candidates.map((m,i)=>`<div class="meal-suggestion"><div><strong>${m.items.map(x=>esc(x.food.emoji+' '+x.food.name)).join(' + ')}</strong><small>${m.items.map(x=>`${Math.round(x.grams)} g ${esc(x.food.name)}`).join(' · ')}</small><small>${Math.round(m.kcal)} kcal · ${Math.round(m.protein)} g protein</small></div><button type="button" class="smart-primary" data-smartmeal="${i}">Add meal</button></div>`).join('');
    qsa('[data-smartmeal]',$('smartMealList')).forEach(b=>b.addEventListener('click',()=>logItems(candidates[+b.dataset.smartmeal].items,meal)));
  }
  $('smartMealType').addEventListener('change',renderComposer); $('smartMealStyle').addEventListener('change',renderComposer); renderComposer();

  const natural=document.createElement('section'); natural.className='smart-card'; natural.innerHTML=`<p class="eyebrow">QUICK LOG WITH WORDS</p><h3>Type it how you would say it</h3><p>Example: “250 g waakye, two eggs, 100 g beef and one spoon of shito.” You can also use foods from the world library.</p><textarea id="nlInput" class="smart-textarea" placeholder="I had 250 g waakye, two eggs and 100 g beef"></textarea><div class="smart-actions"><button id="nlParse" class="smart-primary" type="button">Understand meal</button><button id="nlVoice" class="smart-secondary" type="button">🎙 Dictate</button></div><div id="nlResult"></div>`;
  composer.insertAdjacentElement('afterend',natural);
  const wordNums={one:1,two:2,three:3,four:4,five:5,six:6};
  const aliases=[['groundnut soup','ghana_groundnut_soup'],['palm nut soup','ghana_palmnut_soup'],['cottage cheese','cottage'],['light soup','light_soup'],['waakye','ghana_waakye'],['kontomire','ghana_kontomire_stew'],['jollof','jollof'],['banku','banku'],['kenkey','kenkey'],['fufu','ghana_fufu'],['plantain','plantain'],['yam','yam'],['rice','rice'],['chicken','chicken'],['tilapia','tilapia'],['salmon','salmon'],['beef','beef'],['goat','goat'],['eggs','egg'],['egg','egg'],['sardines','sardines'],['sardine','sardines'],['beans','beans'],['lentils','lentils'],['vegetables','veg'],['veg','veg'],['shito','ghana_shito'],['gari','ghana_gari_dry'],['spaghetti','ghana_spaghetti_cooked'],['avocado','avocado'],['bread','bread'],['okro','okro']];
  function parseSegment(seg){
    const low=seg.toLowerCase(); let match=null; for(const [name,id] of aliases){ if(low.includes(name)){match={name,id};break;} }
    let f=match?resolve(match.id):guessCatalogFood(low); if(!f)return null;
    let grams=null; const gm=low.match(/(\d+(?:\.\d+)?)\s*(?:g|gram|grams)\b/); if(gm) grams=+gm[1]; const kg=low.match(/(\d+(?:\.\d+)?)\s*(?:kg|kilo|kilograms?)\b/); if(kg) grams=+kg[1]*1000;
    const countMatch=low.match(/\b(one|two|three|four|five|six|\d+)\b/); const count=countMatch?(wordNums[countMatch[1]]||+countMatch[1]):null;
    if(grams==null){if(f.id==='egg'&&count) grams=count*50; else if(/tablespoon|tbsp|spoon/.test(low)) grams=(count||1)*15; else if(/teaspoon|tsp/.test(low)) grams=(count||1)*5; else if(f.id==='bread'&&/slice/.test(low)) grams=(count||1)*40;}
    if(grams==null)grams=+f.portion||100; return {id:f.id,food:f,grams:clamp(grams,1,2000)};
  }
  let parsed=[];
  function parseNatural(){
    const text=$('nlInput').value.trim(); if(!text){toast('Type what you ate first');return;} const parts=text.split(/,|\band\b|\+|\bwith\b/i); parsed=parts.map(parseSegment).filter(Boolean);
    if(!parsed.length){$('nlResult').innerHTML='<div class="smart-result">I could not match those foods yet. Try including grams and a food name.</div>';return;}
    $('nlResult').innerHTML=`<div class="parsed-list">${parsed.map((x,i)=>`<div class="parsed-row"><div><strong>${esc(x.food.emoji+' '+x.food.name)}</strong><small>${Math.round(calc(x.food,x.grams).kcal)} kcal</small></div><input class="smart-input" data-nlgrams="${i}" type="number" min="1" value="${Math.round(x.grams)}"><button type="button" class="smart-secondary" data-nldel="${i}">Remove</button></div>`).join('')}</div><div class="smart-row" style="margin-top:10px"><select id="nlMeal" class="smart-select"><option>Lunch</option><option selected>Dinner</option><option>Snack</option><option>Other</option></select><button id="nlAdd" class="smart-primary" type="button">Add all to today</button></div>`;
    qsa('[data-nlgrams]',$('nlResult')).forEach(inp=>inp.addEventListener('input',()=>{parsed[+inp.dataset.nlgrams].grams=clamp(+inp.value||1,1,2000);})); qsa('[data-nldel]',$('nlResult')).forEach(b=>b.addEventListener('click',()=>{parsed.splice(+b.dataset.nldel,1); parseNatural();})); $('nlAdd')?.addEventListener('click',()=>logItems(parsed,$('nlMeal').value));
  }
  $('nlParse').addEventListener('click',parseNatural);
  $('nlVoice').addEventListener('click',()=>{ const SR=window.SpeechRecognition||window.webkitSpeechRecognition; if(!SR){toast('Voice dictation is not available here. Use the keyboard microphone instead.');return;} const r=new SR(); r.lang='en-GB'; r.interimResults=false; r.onresult=e=>{$('nlInput').value=e.results[0][0].transcript;parseNatural();}; r.onerror=()=>toast('Voice dictation could not start'); r.start(); });

  const plate=document.createElement('section'); plate.className='smart-card'; plate.innerHTML=`<p class="eyebrow">GHANAIAN PLATE BUILDER</p><h3>Build the whole plate, not just the starch</h3><p>Useful for waakye, banku, fufu, ampesi and other meals with several extras.</p><div class="plate-grid"><label>Base<select id="plateBase" class="smart-select"></select></label><label>Protein<select id="plateProtein" class="smart-select"></select></label><label>Soup / sauce<select id="plateSauce" class="smart-select"></select></label><label>Extra<select id="plateExtra" class="smart-select"></select></label></div><div id="plateAmounts" class="plate-grid" style="margin-top:10px"></div><div id="plateTotal" class="plate-total"></div><div class="smart-actions"><button id="plateAdd" class="smart-primary" type="button">Add plate to today</button></div>`;
  natural.insertAdjacentElement('afterend',plate);
  const plateGroups={base:[['None',''],['Waakye','ghana_waakye'],['Banku','banku'],['Ga kenkey','kenkey'],['Fufu','ghana_fufu'],['Jollof','jollof'],['Boiled plantain','plantain'],['Yam','yam']],protein:[['None',''],['Tilapia','tilapia'],['Chicken','chicken'],['Beef','beef'],['Goat','goat'],['Egg','egg'],['Sardines','sardines']],sauce:[['None',''],['Okro soup','okro'],['Light soup','light_soup'],['Groundnut soup','ghana_groundnut_soup'],['Palm nut soup','ghana_palmnut_soup'],['Kontomire stew','ghana_kontomire_stew']],extra:[['None',''],['Shito','ghana_shito'],['Gari','ghana_gari_dry'],['Spaghetti','ghana_spaghetti_cooked'],['Avocado','avocado'],['Mixed vegetables','veg']]};
  function fillSelect(id,arr){$(id).innerHTML=arr.map(([n,v])=>`<option value="${esc(v)}">${esc(n)}</option>`).join('');}
  fillSelect('plateBase',plateGroups.base);fillSelect('plateProtein',plateGroups.protein);fillSelect('plateSauce',plateGroups.sauce);fillSelect('plateExtra',plateGroups.extra); $('plateBase').value='ghana_waakye'; $('plateProtein').value='egg'; $('plateExtra').value='ghana_shito';
  let plateItems=[];
  function renderPlate(){ plateItems=['plateBase','plateProtein','plateSauce','plateExtra'].map(id=>$(id).value).filter(Boolean).map(id=>{const f=resolve(id);return f?{id:f.id||id,food:f,grams:+f.portion||100}:null;}).filter(Boolean); $('plateAmounts').innerHTML=plateItems.map((x,i)=>`<label>${esc(x.food.name)}<input class="smart-input" data-plateg="${i}" type="number" min="1" value="${Math.round(x.grams)}"></label>`).join(''); qsa('[data-plateg]',$('plateAmounts')).forEach(inp=>inp.addEventListener('input',()=>{plateItems[+inp.dataset.plateg].grams=clamp(+inp.value||1,1,2000);updatePlateTotal();})); updatePlateTotal(); }
  function updatePlateTotal(){const t=plateItems.reduce((a,x)=>{const c=calc(x.food,x.grams);a.k+=c.kcal;a.p+=c.protein;return a;},{k:0,p:0});$('plateTotal').innerHTML=`<span>Estimated plate total</span><strong>${Math.round(t.k)} kcal · ${Math.round(t.p)} g protein</strong>`;}
  ['plateBase','plateProtein','plateSauce','plateExtra'].forEach(id=>$(id).addEventListener('change',renderPlate)); $('plateAdd').addEventListener('click',()=>logItems(plateItems,'Dinner')); renderPlate();

  const sat=document.createElement('section'); sat.className='smart-card'; sat.innerHTML=`<p class="eyebrow">LEARN WHAT FILLS YOU UP</p><h3>How did your last meal leave you?</h3><p id="satPrompt">Log a meal, then tell the app how satisfied you felt.</p><div class="sat-buttons"><button data-sat="hungry" type="button">Still hungry</button><button data-sat="comfortable" type="button">Comfortable</button><button data-sat="full" type="button">Very full</button></div>`; const todayLog=$('todayLog'); const todayLogCard=todayLog?.closest('.card'); if(todayLogCard) todayLogCard.insertAdjacentElement('afterend',sat); else todayPanel.appendChild(sat);
  function satKey(){const e=todayEntries();return e.length?e[e.length-1].id:null;} function renderSat(){const e=todayEntries();if(!e.length){qsa('[data-sat]',sat).forEach(b=>b.disabled=true);return;} const last=e[e.length-1];$('satPrompt').textContent=`After ${last.name} (${Math.round(last.kcal)} kcal), how did you feel?`; let data={};try{data=JSON.parse(localStorage.getItem(SAT_STORE)||'{}')||{};}catch(_){} const v=data[last.id]; qsa('[data-sat]',sat).forEach(b=>b.classList.toggle('active',b.dataset.sat===v));}
  qsa('[data-sat]',sat).forEach(b=>b.addEventListener('click',()=>{const key=satKey();if(!key)return;let data={};try{data=JSON.parse(localStorage.getItem(SAT_STORE)||'{}')||{};}catch(_){}data[key]=b.dataset.sat;localStorage.setItem(SAT_STORE,JSON.stringify(data));renderSat();toast('Saved. I will use this in your weekly insights.');})); renderSat();

  const ask=document.createElement('section'); ask.className='smart-card'; ask.innerHTML=`<p class="eyebrow">ASK OKELLO</p><h3>Ask about what fits today</h3><p>Try “Can I have jollof tonight?”, “How much banku can I eat?”, “How much biryani fits?” or “What can I eat with 600 calories?”</p><div class="ask-box"><input id="askInput" class="smart-input" placeholder="How much banku can I eat?"><button id="askBtn" class="smart-primary" type="button">Ask</button></div><div id="askResponse"></div>`; sat.insertAdjacentElement('afterend',ask);
  function answerAsk(){const q=$('askInput').value.trim().toLowerCase();if(!q)return;const rem=remaining();let target=rem.kcal;const n=q.match(/(\d{3,4})\s*(?:kcal|calories?)/);if(n)target=Math.min(target,+n[1]);let found=null;for(const [name,id] of aliases){if(q.includes(name)){found=resolve(id);break;}}if(!found)found=guessCatalogFood(q);let text='';if(/what can i eat|what should i eat|meal/.test(q)&&!found){const m=buildMealSuggestion(['tilapia','plantain','veg'],Math.min(target,700));text=m?`A balanced option is ${m.items.map(x=>`${Math.round(x.grams)} g ${x.food.name}`).join(', ')}. That is about ${Math.round(m.kcal)} kcal and ${Math.round(m.protein)} g protein.`:'Use Smart Meal Composer above for a meal suggestion.';}else if(found){const maxg=Math.floor(target/(found.kcal/100)/5)*5;const sensible=Math.min(maxg,+found.max||+found.portion||maxg);text=`Yes. With about ${Math.round(rem.kcal)} kcal left today, ${Math.max(0,sensible)} g of ${found.name} is a sensible upper starting point before any sides or sauce. That portion is about ${Math.round(found.kcal*sensible/100)} kcal.`;}else{text=`You have about ${Math.round(rem.kcal)} kcal and ${Math.round(rem.protein)} g protein left today. Ask me about a specific food from the library, or use Smart Meal Composer above.`;}$('askResponse').innerHTML=`<div class="ask-response">${esc(text)}</div>`;}
  $('askBtn').addEventListener('click',answerAsk);$('askInput').addEventListener('keydown',e=>{if(e.key==='Enter')answerAsk();});

  const labelCard=document.createElement('section');labelCard.className='smart-card';labelCard.innerHTML=`<p class="eyebrow">NUTRITION LABEL SCANNER</p><h3>Photograph the back of a packet</h3><p>The text is read on your device, then calories, protein and fibre are copied into Add food for you to review.</p><input id="labelPhoto" class="smart-input" type="file" accept="image/*" capture="environment"><div id="labelPreview"></div><div id="ocrStatus" class="ocr-progress"></div><div class="smart-actions"><button id="ocrRead" class="smart-primary" type="button">Read nutrition label</button></div>`; const customCard=qs('.custom-food-card',foodsPanel); if(customCard) customCard.insertAdjacentElement('beforebegin',labelCard); else foodsPanel.appendChild(labelCard); let labelFile=null;
  $('labelPhoto').addEventListener('change',e=>{labelFile=e.target.files?.[0]||null;if(!labelFile)return;const u=URL.createObjectURL(labelFile);$('labelPreview').innerHTML=`<img class="label-scan-preview" src="${u}" alt="Nutrition label preview">`;});
  function loadTesseract(){if(window.Tesseract)return Promise.resolve();return new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5.1.1/dist/tesseract.min.js';s.onload=res;s.onerror=rej;document.head.appendChild(s);});}
  function extractNutrition(text){const clean=text.replace(/,/g,'.');const find=(patterns)=>{for(const p of patterns){const m=clean.match(p);if(m)return +m[1];}return null;};let kcal=find([/(?:energy[^\n]{0,30})?(\d{2,4})\s*kcal\b/i,/kcal\s*(\d{2,4})/i]);const protein=find([/protein[^\d]{0,12}(\d+(?:\.\d+)?)\s*g/i]);const fibre=find([/(?:fibre|fiber)[^\d]{0,12}(\d+(?:\.\d+)?)\s*g/i]);return {kcal,protein,fibre};}
  $('ocrRead').addEventListener('click',async()=>{if(!labelFile){toast('Take or choose a label photo first');return;}$('ocrStatus').textContent='Loading text reader…';try{await loadTesseract();const out=await window.Tesseract.recognize(labelFile,'eng',{logger:m=>{if(m.status)$('ocrStatus').textContent=m.status+(m.progress?` ${Math.round(m.progress*100)}%`:'');}});const n=extractNutrition(out.data.text||'');if(n.kcal!=null)$('customKcal').value=n.kcal;if(n.protein!=null)$('customProtein').value=n.protein;if(n.fibre!=null)$('customFibre').value=n.fibre;$('ocrStatus').textContent=`Found ${n.kcal??'—'} kcal, ${n.protein??'—'} g protein, ${n.fibre??'—'} g fibre. Check the values against the label before saving.`;customCard?.scrollIntoView({behavior:'smooth',block:'start'});}catch(e){$('ocrStatus').textContent='I could not read that label. Try a sharper, well-lit photo or enter the values manually.';}});

  const photo=document.createElement('section');photo.className='smart-card';photo.innerHTML=`<p class="eyebrow">PHOTO MEAL CAPTURE · BETA</p><h3>Keep a visual record of the plate</h3><p>Take a photo, then describe the foods. The photo is not used to guess exact grams because that would create false precision.</p><div class="photo-box"><input id="mealPhoto" class="smart-input" type="file" accept="image/*" capture="environment"><div><textarea id="photoNote" class="smart-textarea" placeholder="e.g. waakye, egg, beef, shito"></textarea><button id="photoToWords" class="smart-primary" type="button" style="margin-top:8px">Use description in quick log</button></div></div><div id="mealPhotoPreview"></div>`; labelCard.insertAdjacentElement('afterend',photo);$('mealPhoto').addEventListener('change',e=>{const f=e.target.files?.[0];if(!f)return;const u=URL.createObjectURL(f);$('mealPhotoPreview').innerHTML=`<img class="label-scan-preview" src="${u}" alt="Meal photo preview">`;});$('photoToWords').addEventListener('click',()=>{const v=$('photoNote').value.trim();if(!v){toast('Describe the foods in the photo first');return;}clickTab('today');setTimeout(()=>{$('nlInput').value=v;parseNatural();natural.scrollIntoView({behavior:'smooth',block:'start'});},80);});

  const restaurant=document.createElement('section');restaurant.className='smart-card';restaurant.innerHTML=`<p class="eyebrow">RESTAURANT / TAKEAWAY MODE</p><h3>Log uncertainty instead of pretending</h3><p>Restaurant food varies. Pick the closest dish and the app logs the midpoint of a sensible range.</p><div class="smart-row"><select id="restDish" class="smart-select"><option value="burger">Burger & chips</option><option value="friedrice">Fried rice with chicken</option><option value="ghana">Ghanaian takeaway plate</option><option value="pizza">Pizza, 3 slices</option><option value="kebab">Kebab / grilled meat meal</option><option value="curry">Curry with rice</option></select><select id="restSize" class="smart-select"><option value=".8">Small</option><option value="1" selected>Medium</option><option value="1.25">Large</option></select></div><div id="restEstimate" class="smart-result"></div><div class="smart-actions"><button id="restAdd" class="smart-primary" type="button">Log estimate</button></div>`; photo.insertAdjacentElement('afterend',restaurant);const restRanges={burger:[850,1150,'Burger & chips'],friedrice:[650,950,'Fried rice with chicken'],ghana:[700,1100,'Ghanaian takeaway plate'],pizza:[650,900,'Pizza, 3 slices'],kebab:[600,900,'Kebab / grilled meat meal'],curry:[700,1000,'Curry with rice']};function renderRest(){const [lo,hi,name]=restRanges[$('restDish').value],m=+$('restSize').value;$('restEstimate').innerHTML=`<strong>${Math.round(lo*m)}–${Math.round(hi*m)} kcal</strong><br>Will log midpoint ${Math.round(((lo+hi)/2)*m)} kcal as an estimate.`;}$('restDish').addEventListener('change',renderRest);$('restSize').addEventListener('change',renderRest);$('restAdd').addEventListener('click',()=>{const s=currentState(),k=todayKey(),[lo,hi,name]=restRanges[$('restDish').value],m=+$('restSize').value,mid=((lo+hi)/2)*m;s.logs[k]=s.logs[k]||[];s.logs[k].push({id:uid('log'),foodId:'restaurant_estimate',name,emoji:'🍽️',grams:1,meal:'Dinner',kcal:mid,protein:0,fibre:0,ts:Date.now(),source:'restaurant estimate',range:[lo*m,hi*m]});writeState(s);location.reload();});renderRest();

  const intel=document.createElement('section');intel.className='smart-card';intel.innerHTML=`<p class="eyebrow">WEEKLY INTELLIGENCE</p><h3>What the last 7 days are telling you</h3><div id="intelStats" class="smart-grid three"></div><div id="intelList" class="week-insights" style="margin-top:10px"></div>`;historyPanel.prepend(intel);
  function dateKeys(n){const a=[];for(let i=n-1;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);a.push(d.toISOString().slice(0,10));}return a;}
  function renderIntel(){const s=currentState(),keys=dateKeys(7),days=keys.map(k=>({k,entries:s.logs[k]||[]})).filter(x=>x.entries.length);const dayTotals=days.map(d=>totals(d.entries));const avgK=dayTotals.length?dayTotals.reduce((a,x)=>a+x.kcal,0)/dayTotals.length:0,avgP=dayTotals.length?dayTotals.reduce((a,x)=>a+x.protein,0)/dayTotals.length:0;let satData={};try{satData=JSON.parse(localStorage.getItem(SAT_STORE)||'{}')||{};}catch(_){}const foods={};days.forEach(d=>d.entries.forEach(e=>{foods[e.name]=(foods[e.name]||0)+(+e.kcal||0);}));const top=Object.entries(foods).sort((a,b)=>b[1]-a[1]).slice(0,3);const comfortable=[];days.forEach(d=>d.entries.forEach(e=>{if(satData[e.id]==='comfortable')comfortable.push(e.name);}));const freq=comfortable.reduce((a,n)=>(a[n]=(a[n]||0)+1,a),{});const best=Object.entries(freq).sort((a,b)=>b[1]-a[1])[0]?.[0];$('intelStats').innerHTML=`<div class="smart-stat"><span>Avg calories</span><strong>${Math.round(avgK)||'—'}</strong></div><div class="smart-stat"><span>Avg protein</span><strong>${Math.round(avgP)||'—'}${avgP?' g':''}</strong></div><div class="smart-stat"><span>Logged days</span><strong>${days.length}/7</strong></div>`;const insights=[];if(days.length){if(avgK<=(s.targets.calories||2300))insights.push('Your average intake is at or below your current calorie target.');else insights.push(`Average intake is about ${Math.round(avgK-(s.targets.calories||2300))} kcal above target on logged days.`);if(avgP<(s.targets.protein||150)*.8)insights.push('Protein is running below your target. Build meals around fish, chicken, eggs, cottage cheese or lean meat first.');else insights.push('Protein intake is reasonably close to your target on average.');if(top.length)insights.push(`Biggest calorie contributors: ${top.map(x=>x[0]).join(', ')}.`);if(best)insights.push(`${best} most often left you feeling comfortable after eating.`);}else insights.push('Log a few days and your weekly patterns will appear here.');const weights=s.weightLogs.slice().sort((a,b)=>String(a.date||'').localeCompare(String(b.date||'')));if(weights.length>=2){const recent=weights.slice(-4),first=+recent[0].weight||+recent[0].kg,last=+recent[recent.length-1].weight||+recent[recent.length-1].kg;if(first&&last){const diff=last-first;if(diff<-.5)insights.push('Your recent weight trend is downward. No automatic calorie cut is suggested.');else if(Math.abs(diff)<.3&&days.length>=5&&Math.abs(avgK-(s.targets.calories||2300))<150)insights.push('Weight looks broadly flat while intake is close to target. If that persists for 2–3 more weeks, consider a small target adjustment rather than a large cut.');else insights.push('Weight data is still too noisy for a calorie adjustment. Keep the target steady for now.');}}$('intelList').innerHTML=insights.map(x=>`<div class="insight">${esc(x)}</div>`).join('');}
  renderIntel();

  const smartStatus=document.createElement('section');smartStatus.className='smart-card';smartStatus.innerHTML=`<p class="eyebrow">PERSONAL LEARNING</p><h3>The app gets more useful as you use it</h3><p id="learnStatus"></p><div class="smart-grid"><div class="smart-stat"><span>Foods logged</span><strong id="learnFoods">0</strong></div><div class="smart-stat"><span>Weight readings</span><strong id="learnWeights">0</strong></div></div><p class="tiny-note">All learning in this personal prototype happens on your device. It does not upload your food history to GitHub.</p>`;settingsPanel.appendChild(smartStatus);const st=currentState(),allEntries=Object.values(st.logs).flat();$('learnFoods').textContent=allEntries.length;$('learnWeights').textContent=st.weightLogs.length;$('learnStatus').textContent=allEntries.length<10?'Keep logging meals. Once there is enough history, weekly insights and repeat-meal suggestions become much more meaningful.':'You have enough history for the app to start learning your common foods, portions and patterns.';
})();